// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAKpV4G9qOwdZYVL60JPbtjoVbiu4b0fk',
    appId: '1:725025459044:web:90fbf9fbbe9f59c2e64871',
    messagingSenderId: '725025459044',
    projectId: 'instagramclone-96d7d',
    authDomain: 'instagramclone-96d7d.firebaseapp.com',
    storageBucket: 'instagramclone-96d7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOnIa2XTSADtCLg8QhoCgOrv7cWOaBH_Y',
    appId: '1:725025459044:android:aa86b890ebbfcec2e64871',
    messagingSenderId: '725025459044',
    projectId: 'instagramclone-96d7d',
    storageBucket: 'instagramclone-96d7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl_Ur6Bp6lAGgVNOxGYKlPMztOOZTGK4c',
    appId: '1:725025459044:ios:5564258e26765a17e64871',
    messagingSenderId: '725025459044',
    projectId: 'instagramclone-96d7d',
    storageBucket: 'instagramclone-96d7d.appspot.com',
    iosClientId: '725025459044-cgkhk4vd17a68p3l2gkdsuf7o848flhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaclone',
  );
}
